GH-55 update spring framework to version 5.2.9.RELEASE
pf4j/pf4j-spring pull request #56
Opened 2020-10-23 20:05 UTC by WorkingDevel

This just increases the version of the spring framework dependencies. Running `run-demo.sh` still succeeds.

2020-10-23 21:33 UTC, decebals commented
Did you test it?

2020-10-25 19:00 UTC, WorkingDevel commented
What are the test cases I should test except running the demo app or using it in an app?

2020-10-29 13:00 UTC, m-schroeer requested changes
I'm totally fine with this, but since 2 days v5.3.0 is out, so we should reach for that version.
https://github.com/spring-projects/spring-framework/releases/tag/v5.3.0

2020-10-29 17:53 UTC, merged

2020-10-29 17:54 UTC, decebals commented
@m-schroeer please add a PR for update Spring to 5.3.0